import type { Technology } from "../types";

/**
 * Single source of truth for every supported technology.
 * Adding a new technology requires ONLY adding an entry here -
 * recommendations, skills, ADRs and install scripts pick it up automatically.
 */
export const TECHNOLOGIES: Technology[] = [
  // --- Frameworks ---
  {
    id: "nextjs",
    name: "Next.js",
    category: "framework",
    description: "React framework with App Router, server components and API routes.",
    pricing: "Free and open source",
    freeTier: true,
    docsUrl: "https://nextjs.org/docs",
    pros: ["Full-stack in one codebase", "Excellent DX and ecosystem", "Easy Vercel deployment"],
    cons: ["App Router learning curve", "Server/client boundary complexity"],
    installCommands: ["npm install next react react-dom"],
    envVars: [],
    platforms: ["web", "saas"],
    priority: 1,
  },
  {
    id: "expo",
    name: "Expo (React Native)",
    category: "framework",
    description: "Managed React Native toolchain for iOS, Android and web.",
    pricing: "Free; EAS build services have paid tiers",
    freeTier: true,
    docsUrl: "https://docs.expo.dev",
    pros: ["Fast iteration with Expo Go", "OTA updates", "Single codebase for iOS/Android"],
    cons: ["Some native modules need dev builds", "Binary size overhead"],
    installCommands: ["npx create-expo-app@latest"],
    envVars: [],
    platforms: ["mobile"],
    priority: 1,
  },
  {
    id: "fastify",
    name: "Fastify",
    category: "framework",
    description: "Fast, low-overhead Node.js web framework for APIs.",
    pricing: "Free and open source",
    freeTier: true,
    docsUrl: "https://fastify.dev/docs/latest",
    pros: ["High performance", "Schema-based validation", "Plugin ecosystem"],
    cons: ["Smaller ecosystem than Express"],
    installCommands: ["npm install fastify"],
    envVars: [],
    platforms: ["backend"],
    priority: 1,
  },
  {
    id: "plasmo",
    name: "Plasmo",
    category: "framework",
    description: "Framework for building browser extensions with React.",
    pricing: "Free and open source",
    freeTier: true,
    docsUrl: "https://docs.plasmo.com",
    pros: ["Hot reload for extensions", "Manifest v3 ready", "React-first"],
    cons: ["Smaller community"],
    installCommands: ["npm install plasmo"],
    envVars: [],
    platforms: ["chrome-extension"],
    priority: 1,
  },
  {
    id: "vercel-ai-sdk",
    name: "Vercel AI SDK",
    category: "framework",
    description: "TypeScript toolkit for building AI and agentic applications.",
    pricing: "Free and open source",
    freeTier: true,
    docsUrl: "https://sdk.vercel.ai/docs",
    pros: ["Provider-agnostic", "Streaming and tool-calling built in", "Great TypeScript support"],
    cons: ["Fast-moving API surface"],
    installCommands: ["npm install ai"],
    envVars: [],
    platforms: ["agentic"],
    priority: 1,
  },
  // --- Authentication ---
  {
    id: "clerk",
    name: "Clerk",
    category: "authentication",
    description: "Drop-in authentication and user management with prebuilt UI.",
    pricing: "Free up to 10,000 MAU, then from $25/mo",
    freeTier: true,
    docsUrl: "https://clerk.com/docs",
    pros: ["Best-in-class DX", "Prebuilt components", "MFA, orgs, social login"],
    cons: ["Vendor lock-in", "Costs grow with MAU"],
    installCommands: ["npm install @clerk/nextjs"],
    platformInstallCommands: {
      mobile: ["npm install @clerk/clerk-expo expo-web-browser expo-secure-store"],
      web: ["npm install @clerk/nextjs"],
      saas: ["npm install @clerk/nextjs"],
    },
    envVars: ["NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY", "CLERK_SECRET_KEY"],
    platforms: ["web", "mobile", "saas"],
    priority: 1,
  },
  {
    id: "better-auth",
    name: "Better Auth",
    category: "authentication",
    description: "Open-source, framework-agnostic authentication library.",
    pricing: "Free and open source",
    freeTier: true,
    docsUrl: "https://www.better-auth.com/docs",
    pros: ["No vendor lock-in", "Owns your user data", "Plugin system"],
    cons: ["You manage infrastructure", "Younger project"],
    installCommands: ["npm install better-auth"],
    envVars: ["BETTER_AUTH_SECRET", "BETTER_AUTH_URL"],
    platforms: ["web", "backend", "saas"],
    priority: 2,
  },
  {
    id: "supabase-auth",
    name: "Supabase Auth",
    category: "authentication",
    description: "Authentication bundled with the Supabase platform.",
    pricing: "Included in Supabase free tier",
    freeTier: true,
    docsUrl: "https://supabase.com/docs/guides/auth",
    pros: ["Integrates with Supabase DB and RLS", "Generous free tier"],
    cons: ["Less polished UI components", "Tied to Supabase"],
    installCommands: ["npm install @supabase/supabase-js"],
    envVars: ["NEXT_PUBLIC_SUPABASE_URL", "NEXT_PUBLIC_SUPABASE_ANON_KEY"],
    platforms: ["web", "mobile", "backend", "saas"],
    priority: 3,
  },
  // --- State management ---
  {
    id: "zustand",
    name: "Zustand",
    category: "stateManagement",
    description: "Small, fast, unopinionated state management for React.",
    pricing: "Free and open source",
    freeTier: true,
    docsUrl: "https://docs.pmnd.rs/zustand",
    pros: ["Minimal boilerplate", "Tiny bundle", "Works outside React"],
    cons: ["Fewer conventions for large teams"],
    installCommands: ["npm install zustand"],
    envVars: [],
    platforms: ["web", "mobile", "saas", "chrome-extension"],
    priority: 1,
  },
  {
    id: "redux-toolkit",
    name: "Redux Toolkit",
    category: "stateManagement",
    description: "Official, batteries-included Redux state management.",
    pricing: "Free and open source",
    freeTier: true,
    docsUrl: "https://redux-toolkit.js.org",
    pros: ["Strong conventions", "Excellent devtools", "Large community"],
    cons: ["More boilerplate than Zustand"],
    installCommands: ["npm install @reduxjs/toolkit react-redux"],
    envVars: [],
    platforms: ["web", "mobile", "saas", "chrome-extension"],
    priority: 2,
  },
  // --- Database ---
  {
    id: "supabase",
    name: "Supabase",
    category: "database",
    description: "Hosted Postgres with realtime, auth, storage and edge functions.",
    pricing: "Free tier (500MB DB), Pro from $25/mo",
    freeTier: true,
    docsUrl: "https://supabase.com/docs",
    pros: ["Postgres + RLS", "Realtime subscriptions", "Generous free tier"],
    cons: ["Free projects pause after inactivity"],
    installCommands: ["npm install @supabase/supabase-js"],
    envVars: ["NEXT_PUBLIC_SUPABASE_URL", "NEXT_PUBLIC_SUPABASE_ANON_KEY"],
    platforms: ["web", "mobile", "backend", "saas", "agentic"],
    priority: 1,
  },
  {
    id: "postgresql",
    name: "PostgreSQL (self-hosted)",
    category: "database",
    description: "The world's most advanced open-source relational database.",
    pricing: "Free; hosting costs vary",
    freeTier: true,
    docsUrl: "https://www.postgresql.org/docs",
    pros: ["Full control", "No vendor lock-in", "Battle tested"],
    cons: ["You manage backups, scaling and security"],
    installCommands: ["npm install pg"],
    envVars: ["DATABASE_URL"],
    platforms: ["web", "backend", "saas", "agentic"],
    priority: 2,
  },
  {
    id: "mongodb",
    name: "MongoDB Atlas",
    category: "database",
    description: "Hosted document database with a flexible schema.",
    pricing: "Free M0 tier, paid from ~$9/mo",
    freeTier: true,
    docsUrl: "https://www.mongodb.com/docs/atlas",
    pros: ["Flexible documents", "Easy horizontal scaling"],
    cons: ["Weaker relational guarantees", "Query model differs from SQL"],
    installCommands: ["npm install mongodb"],
    envVars: ["MONGODB_URI"],
    platforms: ["web", "backend", "saas", "agentic"],
    priority: 3,
  },
  // --- AI ---
  {
    id: "gemini",
    name: "Google Gemini",
    category: "ai",
    description: "Google's multimodal LLM API with a generous free tier.",
    pricing: "Generous free tier; pay-as-you-go beyond",
    freeTier: true,
    docsUrl: "https://ai.google.dev/gemini-api/docs",
    pros: ["Best free tier among major providers", "Long context", "Multimodal"],
    cons: ["Rate limits on free tier"],
    installCommands: ["npm install @google/generative-ai"],
    envVars: ["GEMINI_API_KEY"],
    platforms: ["web", "mobile", "backend", "saas", "agentic"],
    priority: 1,
  },
  {
    id: "openai",
    name: "OpenAI",
    category: "ai",
    description: "GPT model family API for chat, embeddings and tools.",
    pricing: "Pay-as-you-go, no free tier",
    freeTier: false,
    docsUrl: "https://platform.openai.com/docs",
    pros: ["Strong tool-calling", "Large ecosystem"],
    cons: ["No free tier", "Costs scale with usage"],
    installCommands: ["npm install openai"],
    envVars: ["OPENAI_API_KEY"],
    platforms: ["web", "mobile", "backend", "saas", "agentic"],
    priority: 2,
  },
  {
    id: "anthropic",
    name: "Anthropic Claude",
    category: "ai",
    description: "Claude model family API, strong at reasoning and coding.",
    pricing: "Pay-as-you-go, no free tier",
    freeTier: false,
    docsUrl: "https://docs.anthropic.com",
    pros: ["Excellent long-form reasoning", "Large context windows"],
    cons: ["No free tier"],
    installCommands: ["npm install @anthropic-ai/sdk"],
    envVars: ["ANTHROPIC_API_KEY"],
    platforms: ["web", "mobile", "backend", "saas", "agentic"],
    priority: 3,
  },
  // --- Video ---
  {
    id: "stream",
    name: "Stream Video",
    category: "video",
    description: "Hosted video calling, livestreaming and chat SDKs.",
    pricing: "Free maker plan for small apps; paid from $499/mo",
    freeTier: true,
    docsUrl: "https://getstream.io/video/docs",
    pros: ["Polished SDKs for React/React Native", "Chat included"],
    cons: ["Expensive at scale"],
    installCommands: ["npm install @stream-io/video-react-sdk"],
    envVars: ["STREAM_API_KEY", "STREAM_API_SECRET"],
    platforms: ["web", "mobile", "saas"],
    priority: 1,
  },
  {
    id: "livekit",
    name: "LiveKit",
    category: "video",
    description: "Open-source WebRTC infrastructure, cloud or self-hosted.",
    pricing: "Free cloud tier; self-hosting is free",
    freeTier: true,
    docsUrl: "https://docs.livekit.io",
    pros: ["Open source", "Self-host option", "Good realtime AI support"],
    cons: ["More setup than Stream"],
    installCommands: ["npm install livekit-client"],
    envVars: ["LIVEKIT_API_KEY", "LIVEKIT_API_SECRET", "LIVEKIT_URL"],
    platforms: ["web", "mobile", "saas", "agentic"],
    priority: 2,
  },
  // --- Storage ---
  {
    id: "supabase-storage",
    name: "Supabase Storage",
    category: "storage",
    description: "S3-compatible object storage bundled with Supabase.",
    pricing: "1GB free, then usage-based",
    freeTier: true,
    docsUrl: "https://supabase.com/docs/guides/storage",
    pros: ["Integrates with Supabase auth/RLS", "Simple API"],
    cons: ["Tied to Supabase"],
    installCommands: ["npm install @supabase/supabase-js"],
    envVars: ["NEXT_PUBLIC_SUPABASE_URL", "NEXT_PUBLIC_SUPABASE_ANON_KEY"],
    platforms: ["web", "mobile", "backend", "saas", "agentic", "chrome-extension"],
    priority: 1,
  },
  {
    id: "cloudflare-r2",
    name: "Cloudflare R2",
    category: "storage",
    description: "S3-compatible object storage with zero egress fees.",
    pricing: "10GB free, no egress fees",
    freeTier: true,
    docsUrl: "https://developers.cloudflare.com/r2",
    pros: ["No egress fees", "S3 compatible"],
    cons: ["Requires Cloudflare account setup"],
    installCommands: ["npm install @aws-sdk/client-s3"],
    envVars: ["R2_ACCOUNT_ID", "R2_ACCESS_KEY_ID", "R2_SECRET_ACCESS_KEY"],
    platforms: ["web", "backend", "saas", "agentic", "chrome-extension"],
    priority: 2,
  },
  // --- Email ---
  {
    id: "resend",
    name: "Resend",
    category: "email",
    description: "Developer-first transactional email API with React Email support.",
    pricing: "3,000 emails/mo free, then from $20/mo",
    freeTier: true,
    docsUrl: "https://resend.com/docs",
    pros: ["Great DX", "React Email templates", "Generous free tier"],
    cons: ["Younger than SendGrid/Mailgun"],
    installCommands: ["npm install resend"],
    envVars: ["RESEND_API_KEY"],
    platforms: ["web", "backend", "saas"],
    priority: 1,
  },
  // --- Payments ---
  {
    id: "stripe",
    name: "Stripe",
    category: "payments",
    description: "Industry-standard payments, subscriptions and billing.",
    pricing: "No monthly fee; 2.9% + 30c per transaction",
    freeTier: false,
    docsUrl: "https://docs.stripe.com",
    pros: ["Best-in-class docs", "Subscriptions, invoicing, tax"],
    cons: ["Transaction fees", "Complex for advanced billing"],
    installCommands: ["npm install stripe"],
    envVars: ["STRIPE_SECRET_KEY", "STRIPE_WEBHOOK_SECRET"],
    platforms: ["web", "mobile", "backend", "saas"],
    priority: 1,
  },
  // --- Analytics ---
  {
    id: "posthog",
    name: "PostHog",
    category: "analytics",
    description: "Open-source product analytics, session replay and feature flags.",
    pricing: "1M events/mo free, then usage-based",
    freeTier: true,
    docsUrl: "https://posthog.com/docs",
    pros: ["All-in-one product suite", "Self-host option", "Generous free tier"],
    cons: ["UI can feel dense"],
    installCommands: ["npm install posthog-js"],
    envVars: ["NEXT_PUBLIC_POSTHOG_KEY", "NEXT_PUBLIC_POSTHOG_HOST"],
    platforms: ["web", "mobile", "saas", "chrome-extension"],
    priority: 1,
  },
  // --- Monitoring ---
  {
    id: "sentry",
    name: "Sentry",
    category: "monitoring",
    description: "Error tracking and performance monitoring.",
    pricing: "Free developer tier, paid from $26/mo",
    freeTier: true,
    docsUrl: "https://docs.sentry.io",
    pros: ["Rich error context", "Wide SDK coverage"],
    cons: ["Quota limits on free tier"],
    installCommands: ["npm install @sentry/nextjs"],
    envVars: ["SENTRY_DSN"],
    platforms: ["web", "mobile", "backend", "saas", "agentic"],
    priority: 1,
  },
  // --- Styling ---
  {
    id: "tailwind",
    name: "Tailwind CSS",
    category: "styling",
    description: "Utility-first CSS framework.",
    pricing: "Free and open source",
    freeTier: true,
    docsUrl: "https://tailwindcss.com/docs",
    pros: ["Fast iteration", "Design consistency via tokens"],
    cons: ["Verbose class lists"],
    installCommands: ["npm install -D tailwindcss postcss autoprefixer"],
    envVars: [],
    platforms: ["web", "saas", "chrome-extension"],
    priority: 1,
  },
  {
    id: "nativewind",
    name: "NativeWind",
    category: "styling",
    description: "Tailwind CSS for React Native.",
    pricing: "Free and open source",
    freeTier: true,
    docsUrl: "https://www.nativewind.dev",
    pros: ["Tailwind syntax on mobile", "Shared design language with web"],
    cons: ["Subset of Tailwind features"],
    installCommands: ["npm install nativewind", "npm install -D tailwindcss"],
    envVars: [],
    platforms: ["mobile"],
    priority: 1,
  },
  // --- Hosting ---
  {
    id: "vercel",
    name: "Vercel",
    category: "hosting",
    description: "Zero-config hosting for Next.js and frontend frameworks with edge network.",
    pricing: "Free hobby tier; Pro from $20/user/mo",
    freeTier: true,
    docsUrl: "https://vercel.com/docs",
    pros: ["Best-in-class Next.js integration", "Preview deployments per branch"],
    cons: ["Costs scale quickly with traffic", "Vendor-specific features"],
    installCommands: ["npm install -D vercel"],
    envVars: [],
    platforms: ["web", "saas", "backend"],
    priority: 1,
  },
  {
    id: "netlify",
    name: "Netlify",
    category: "hosting",
    description: "Hosting platform for static sites and serverless functions.",
    pricing: "Free starter tier; Pro from $19/user/mo",
    freeTier: true,
    docsUrl: "https://docs.netlify.com",
    pros: ["Simple deploys", "Generous free tier", "Forms and edge functions built in"],
    cons: ["Less optimized for Next.js than Vercel"],
    installCommands: ["npm install -D netlify-cli"],
    envVars: [],
    platforms: ["web", "saas"],
    priority: 2,
  },
  {
    id: "railway",
    name: "Railway",
    category: "hosting",
    description: "Container hosting for backends, workers and databases.",
    pricing: "Usage-based; ~$5/mo minimum after trial",
    freeTier: false,
    docsUrl: "https://docs.railway.com",
    pros: ["Runs anything in a container", "Built-in Postgres/Redis"],
    cons: ["No permanent free tier"],
    installCommands: ["npm install -D @railway/cli"],
    envVars: [],
    platforms: ["backend", "saas", "agentic"],
    priority: 3,
  },
  // --- Phase 2 registry buildout ---
  {
    id: "auth0",
    name: "Auth0",
    category: "authentication",
    description: "Enterprise-grade identity platform with extensive protocol support.",
    pricing: "Free up to 25,000 MAU; paid tiers beyond",
    freeTier: true,
    docsUrl: "https://auth0.com/docs",
    pros: ["Mature enterprise features", "Broad protocol/SSO support"],
    cons: ["Complex configuration", "Pricing jumps at scale"],
    installCommands: ["npm install @auth0/nextjs-auth0"],
    envVars: ["AUTH0_SECRET", "AUTH0_BASE_URL", "AUTH0_ISSUER_BASE_URL", "AUTH0_CLIENT_ID", "AUTH0_CLIENT_SECRET"],
    platforms: ["web", "mobile", "saas", "backend"],
    priority: 4,
  },
  {
    id: "neon",
    name: "Neon",
    category: "database",
    description: "Serverless Postgres with branching and scale-to-zero.",
    pricing: "Free tier (0.5GB); paid from $19/mo",
    freeTier: true,
    docsUrl: "https://neon.com/docs",
    pros: ["Database branching for previews", "Scale to zero", "Plain Postgres"],
    cons: ["Cold starts on free tier"],
    installCommands: ["npm install @neondatabase/serverless"],
    envVars: ["DATABASE_URL"],
    platforms: ["web", "backend", "saas", "agentic"],
    priority: 4,
  },
  {
    id: "lemon-squeezy",
    name: "Lemon Squeezy",
    category: "payments",
    description: "Merchant-of-record payments for digital products and SaaS.",
    pricing: "5% + 50c per transaction; no monthly fee",
    freeTier: false,
    docsUrl: "https://docs.lemonsqueezy.com",
    pros: ["Handles global sales tax as merchant of record", "Simple setup"],
    cons: ["Higher per-transaction fee than Stripe"],
    installCommands: ["npm install @lemonsqueezy/lemonsqueezy.js"],
    envVars: ["LEMONSQUEEZY_API_KEY", "LEMONSQUEEZY_WEBHOOK_SECRET"],
    platforms: ["web", "saas"],
    priority: 2,
  },
  {
    id: "plausible",
    name: "Plausible",
    category: "analytics",
    description: "Lightweight, privacy-first, cookieless web analytics.",
    pricing: "From $9/mo; free when self-hosted",
    freeTier: true,
    docsUrl: "https://plausible.io/docs",
    pros: ["No cookie banners needed", "Tiny script", "Self-host option"],
    cons: ["No session replay or product analytics depth"],
    installCommands: ["npm install next-plausible"],
    envVars: [],
    platforms: ["web", "saas"],
    priority: 2,
  },
  {
    id: "sendgrid",
    name: "SendGrid",
    category: "email",
    description: "Established transactional and marketing email platform.",
    pricing: "Free 100 emails/day; paid from $19.95/mo",
    freeTier: true,
    docsUrl: "https://www.twilio.com/docs/sendgrid",
    pros: ["Battle-tested deliverability", "Marketing + transactional in one"],
    cons: ["Dated DX compared to Resend"],
    installCommands: ["npm install @sendgrid/mail"],
    envVars: ["SENDGRID_API_KEY"],
    platforms: ["web", "backend", "saas"],
    priority: 2,
  },
  // --- Data Fetching ---
  {
    id: "tanstack-query",
    name: "TanStack Query",
    category: "dataFetching",
    description: "Powerful asynchronous state management and data fetching.",
    pricing: "Free and open source",
    freeTier: true,
    docsUrl: "https://tanstack.com/query/latest",
    pros: ["Caching, deduplication and background updates out of the box", "Agnostic to data fetching method"],
    cons: ["Adds some bundle size"],
    installCommands: ["npm install @tanstack/react-query"],
    envVars: [],
    platforms: ["web", "mobile", "saas", "chrome-extension"],
    priority: 1,
  },
  // --- Speech Recognition ---
  {
    id: "whisper",
    name: "Whisper (OpenAI)",
    category: "speechRecognition",
    description: "Robust open-source speech recognition model by OpenAI.",
    pricing: "Paid via API; Free if self-hosted",
    freeTier: false,
    docsUrl: "https://platform.openai.com/docs/guides/speech-to-text",
    pros: ["Highly accurate across many languages", "Robust to background noise"],
    cons: ["Slower than streaming alternatives without optimization"],
    installCommands: ["npm install openai"],
    envVars: ["OPENAI_API_KEY"],
    platforms: ["web", "mobile", "saas", "agentic"],
    priority: 1,
  },
  {
    id: "google-speech-to-text",
    name: "Google Speech-to-Text",
    category: "speechRecognition",
    description: "Google Cloud's powerful speech recognition API.",
    pricing: "Usage-based with free tier (60 mins/month)",
    freeTier: true,
    docsUrl: "https://cloud.google.com/speech-to-text",
    pros: ["Excellent streaming support", "Massive language coverage"],
    cons: ["Google Cloud setup can be complex"],
    installCommands: ["npm install @google-cloud/speech"],
    envVars: ["GOOGLE_APPLICATION_CREDENTIALS"],
    platforms: ["web", "mobile", "saas"],
    priority: 2,
  },
  // --- Text-to-Speech ---
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    category: "textToSpeech",
    description: "Industry-leading hyper-realistic AI voice generator.",
    pricing: "Free tier available (10k chars/mo); Paid from $5/mo",
    freeTier: true,
    docsUrl: "https://elevenlabs.io/docs",
    pros: ["Unmatched voice realism", "Voice cloning capabilities"],
    cons: ["Can get expensive with high usage"],
    installCommands: ["npm install elevenlabs-node"], // Optional, often just REST calls
    envVars: ["ELEVENLABS_API_KEY"],
    platforms: ["web", "mobile", "saas", "agentic"],
    priority: 1,
  },
  {
    id: "google-tts",
    name: "Google Cloud TTS",
    category: "textToSpeech",
    description: "Google's Text-to-Speech service offering Studio and Wavenet voices.",
    pricing: "Generous free tier (up to 1M chars/mo depending on voice type)",
    freeTier: true,
    docsUrl: "https://cloud.google.com/text-to-speech",
    pros: ["Highly reliable", "Large free tier"],
    cons: ["Voices sound slightly more robotic than ElevenLabs"],
    installCommands: ["npm install @google-cloud/text-to-speech"],
    envVars: ["GOOGLE_APPLICATION_CREDENTIALS"],
    platforms: ["web", "mobile", "saas"],
    priority: 2,
  },
  // --- Notifications ---
  {
    id: "expo-notifications",
    name: "Expo Notifications",
    category: "notifications",
    description: "Push notifications for React Native applications built with Expo.",
    pricing: "Free and open source",
    freeTier: true,
    docsUrl: "https://docs.expo.dev/versions/latest/sdk/notifications/",
    pros: ["Seamless Expo integration", "Handles both local and push notifications"],
    cons: ["Requires EAS or external push service for scale"],
    installCommands: ["npx expo install expo-notifications expo-device"],
    envVars: [],
    platforms: ["mobile"],
    priority: 1,
  },
  // --- New Categories (Score Improvement) ---
  {
    id: "drizzle",
    name: "Drizzle ORM",
    category: "orm",
    description: "Lightweight, TypeScript-first ORM with excellent performance.",
    pricing: "Free and open source",
    freeTier: true,
    docsUrl: "https://orm.drizzle.team",
    pros: ["Type-safe SQL", "Edge-ready", "No Rust dependency"],
    cons: ["Younger ecosystem than Prisma"],
    installCommands: ["npm install drizzle-orm", "npm install -D drizzle-kit"],
    envVars: ["DATABASE_URL"],
    platforms: ["web", "backend", "saas", "agentic"],
    priority: 1,
  },
  {
    id: "prisma",
    name: "Prisma",
    category: "orm",
    description: "Next-generation Node.js and TypeScript ORM.",
    pricing: "Free and open source",
    freeTier: true,
    docsUrl: "https://www.prisma.io/docs",
    pros: ["Excellent DX", "Automated migrations", "Intuitive schema"],
    cons: ["Rust engine overhead", "Heavy cold starts"],
    installCommands: ["npm install prisma @prisma/client"],
    envVars: ["DATABASE_URL"],
    platforms: ["web", "backend", "saas"],
    priority: 2,
  },
  {
    id: "vitest",
    name: "Vitest",
    category: "testing",
    description: "Next generation testing framework powered by Vite.",
    pricing: "Free and open source",
    freeTier: true,
    docsUrl: "https://vitest.dev",
    pros: ["Fast", "Vite compatible", "Native ESM"],
    cons: ["Newer than Jest"],
    installCommands: ["npm install -D vitest"],
    envVars: [],
    platforms: ["web", "backend", "saas"],
    priority: 1,
  },
  {
    id: "playwright",
    name: "Playwright",
    category: "testing",
    description: "End-to-end testing for modern web apps.",
    pricing: "Free and open source",
    freeTier: true,
    docsUrl: "https://playwright.dev",
    pros: ["Cross-browser", "Reliable auto-waiting", "Excellent trace viewer"],
    cons: ["Steep learning curve for advanced features"],
    installCommands: ["npm init playwright@latest"],
    envVars: [],
    platforms: ["web", "saas"],
    priority: 2,
  },
  {
    id: "vite",
    name: "Vite",
    category: "bundler",
    description: "Next generation frontend tooling.",
    pricing: "Free and open source",
    freeTier: true,
    docsUrl: "https://vitejs.dev",
    pros: ["Instant server start", "Lightning fast HMR"],
    cons: ["Rollup for prod vs esbuild for dev can cause subtle differences"],
    installCommands: ["npm install -D vite"],
    envVars: [],
    platforms: ["web", "chrome-extension"],
    priority: 1,
  },
  {
    id: "bun",
    name: "Bun",
    category: "runtime",
    description: "Fast all-in-one JavaScript runtime.",
    pricing: "Free and open source",
    freeTier: true,
    docsUrl: "https://bun.sh",
    pros: ["Incredibly fast", "Built-in bundler/test runner"],
    cons: ["Not 100% Node compatible yet"],
    installCommands: ["curl -fsSL https://bun.sh/install | bash"],
    envVars: [],
    platforms: ["backend", "agentic"],
    priority: 1,
  },
  {
    id: "react-hook-form",
    name: "React Hook Form",
    category: "forms",
    description: "Performant, flexible and extensible forms with easy-to-use validation.",
    pricing: "Free and open source",
    freeTier: true,
    docsUrl: "https://react-hook-form.com",
    pros: ["Performant (fewer re-renders)", "Tiny bundle size"],
    cons: ["Controlled inputs require Controller wrapper"],
    installCommands: ["npm install react-hook-form @hookform/resolvers zod"],
    envVars: [],
    platforms: ["web", "saas", "mobile"],
    priority: 1,
  },
  {
    id: "conform",
    name: "Conform",
    category: "forms",
    description: "Type-safe form validation library for Remix and Next.js.",
    pricing: "Free and open source",
    freeTier: true,
    docsUrl: "https://conform.guide",
    pros: ["Progressive enhancement", "First-class Zod support"],
    cons: ["Requires server-side validation setup"],
    installCommands: ["npm install @conform-to/react @conform-to/zod"],
    envVars: [],
    platforms: ["web", "saas"],
    priority: 2,
  },
  {
    id: "remix",
    name: "Remix",
    category: "framework",
    description: "Full stack web framework that lets you focus on the user interface.",
    pricing: "Free and open source",
    freeTier: true,
    docsUrl: "https://remix.run",
    pros: ["Web standards focused", "Excellent nested routing", "Data loading model"],
    cons: ["Smaller ecosystem than Next.js"],
    installCommands: ["npx create-remix@latest"],
    envVars: [],
    platforms: ["web", "saas"],
    priority: 3,
  },
  {
    id: "sveltekit",
    name: "SvelteKit",
    category: "framework",
    description: "Web development, streamlined. The fastest way to build Svelte apps.",
    pricing: "Free and open source",
    freeTier: true,
    docsUrl: "https://kit.svelte.dev",
    pros: ["Incredible DX", "Tiny bundle sizes", "No virtual DOM overhead"],
    cons: ["Ecosystem is smaller than React"],
    installCommands: ["npm create svelte@latest"],
    envVars: [],
    platforms: ["web"],
    priority: 4,
  },
  {
    id: "fly-io",
    name: "Fly.io",
    category: "hosting",
    description: "Deploy app servers close to your users.",
    pricing: "Pay as you go",
    freeTier: false,
    docsUrl: "https://fly.io/docs",
    pros: ["Global deployments", "Persistent volumes", "Runs any Dockerfile"],
    cons: ["No permanent free tier", "Platform stability can occasionally fluctuate"],
    installCommands: ["curl -L https://fly.io/install.sh | sh"],
    envVars: [],
    platforms: ["backend", "saas", "agentic"],
    priority: 4,
  },
];

export function getTechnologyById(id: string): Technology | undefined {
  return TECHNOLOGIES.find((t) => t.id === id);
}
