import type { Technology } from "../types";

/**
 * Single source of truth for every supported technology.
 * Adding a new technology requires ONLY adding an entry here -
 * recommendations, skills, ADRs and install scripts pick it up automatically.
 */
export const TECHNOLOGIES: Technology[] = [
  // --- Frameworks ---
  {
    id: "nextjs",
    name: "Next.js",
    category: "framework",
    description: "React framework with App Router, server components and API routes.",
    pricing: "Free and open source",
    freeTier: true,
    docsUrl: "https://nextjs.org/docs",
    pros: ["Full-stack in one codebase", "Excellent DX and ecosystem", "Easy Vercel deployment"],
    cons: ["App Router learning curve", "Server/client boundary complexity"],
    installCommands: ["npm install next react react-dom"],
    envVars: [],
    platforms: ["web", "saas"],
    priority: 1,
  },
  {
    id: "expo",
    name: "Expo (React Native)",
    category: "framework",
    description: "Managed React Native toolchain for iOS, Android and web.",
    pricing: "Free; EAS build services have paid tiers",
    freeTier: true,
    docsUrl: "https://docs.expo.dev",
    pros: ["Fast iteration with Expo Go", "OTA updates", "Single codebase for iOS/Android"],
    cons: ["Some native modules need dev builds", "Binary size overhead"],
    installCommands: ["npx create-expo-app@latest"],
    envVars: [],
    platforms: ["mobile"],
    priority: 1,
  },
  {
    id: "fastify",
    name: "Fastify",
    category: "framework",
    description: "Fast, low-overhead Node.js web framework for APIs.",
    pricing: "Free and open source",
    freeTier: true,
    docsUrl: "https://fastify.dev/docs/latest",
    pros: ["High performance", "Schema-based validation", "Plugin ecosystem"],
    cons: ["Smaller ecosystem than Express"],
    installCommands: ["npm install fastify"],
    envVars: [],
    platforms: ["backend"],
    priority: 1,
  },
  {
    id: "plasmo",
    name: "Plasmo",
    category: "framework",
    description: "Framework for building browser extensions with React.",
    pricing: "Free and open source",
    freeTier: true,
    docsUrl: "https://docs.plasmo.com",
    pros: ["Hot reload for extensions", "Manifest v3 ready", "React-first"],
    cons: ["Smaller community"],
    installCommands: ["npm install plasmo"],
    envVars: [],
    platforms: ["chrome-extension"],
    priority: 1,
  },
  {
    id: "vercel-ai-sdk",
    name: "Vercel AI SDK",
    category: "framework",
    description: "TypeScript toolkit for building AI and agentic applications.",
    pricing: "Free and open source",
    freeTier: true,
    docsUrl: "https://sdk.vercel.ai/docs",
    pros: ["Provider-agnostic", "Streaming and tool-calling built in", "Great TypeScript support"],
    cons: ["Fast-moving API surface"],
    installCommands: ["npm install ai"],
    envVars: [],
    platforms: ["agentic"],
    priority: 1,
  },
  // --- Authentication ---
  {
    id: "clerk",
    name: "Clerk",
    category: "authentication",
    description: "Drop-in authentication and user management with prebuilt UI.",
    pricing: "Free up to 10,000 MAU, then from $25/mo",
    freeTier: true,
    docsUrl: "https://clerk.com/docs",
    pros: ["Best-in-class DX", "Prebuilt components", "MFA, orgs, social login"],
    cons: ["Vendor lock-in", "Costs grow with MAU"],
    installCommands: ["npm install @clerk/nextjs"],
    envVars: ["NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY", "CLERK_SECRET_KEY"],
    platforms: ["web", "mobile", "saas"],
    priority: 1,
  },
  {
    id: "better-auth",
    name: "Better Auth",
    category: "authentication",
    description: "Open-source, framework-agnostic authentication library.",
    pricing: "Free and open source",
    freeTier: true,
    docsUrl: "https://www.better-auth.com/docs",
    pros: ["No vendor lock-in", "Owns your user data", "Plugin system"],
    cons: ["You manage infrastructure", "Younger project"],
    installCommands: ["npm install better-auth"],
    envVars: ["BETTER_AUTH_SECRET", "BETTER_AUTH_URL"],
    platforms: ["web", "backend", "saas"],
    priority: 2,
  },
  {
    id: "supabase-auth",
    name: "Supabase Auth",
    category: "authentication",
    description: "Authentication bundled with the Supabase platform.",
    pricing: "Included in Supabase free tier",
    freeTier: true,
    docsUrl: "https://supabase.com/docs/guides/auth",
    pros: ["Integrates with Supabase DB and RLS", "Generous free tier"],
    cons: ["Less polished UI components", "Tied to Supabase"],
    installCommands: ["npm install @supabase/supabase-js"],
    envVars: ["NEXT_PUBLIC_SUPABASE_URL", "NEXT_PUBLIC_SUPABASE_ANON_KEY"],
    platforms: ["web", "mobile", "backend", "saas"],
    priority: 3,
  },
  // --- State management ---
  {
    id: "zustand",
    name: "Zustand",
    category: "stateManagement",
    description: "Small, fast, unopinionated state management for React.",
    pricing: "Free and open source",
    freeTier: true,
    docsUrl: "https://docs.pmnd.rs/zustand",
    pros: ["Minimal boilerplate", "Tiny bundle", "Works outside React"],
    cons: ["Fewer conventions for large teams"],
    installCommands: ["npm install zustand"],
    envVars: [],
    platforms: ["web", "mobile", "saas", "chrome-extension"],
    priority: 1,
  },
  {
    id: "redux-toolkit",
    name: "Redux Toolkit",
    category: "stateManagement",
    description: "Official, batteries-included Redux state management.",
    pricing: "Free and open source",
    freeTier: true,
    docsUrl: "https://redux-toolkit.js.org",
    pros: ["Strong conventions", "Excellent devtools", "Large community"],
    cons: ["More boilerplate than Zustand"],
    installCommands: ["npm install @reduxjs/toolkit react-redux"],
    envVars: [],
    platforms: ["web", "mobile", "saas", "chrome-extension"],
    priority: 2,
  },
  // --- Database ---
  {
    id: "supabase",
    name: "Supabase",
    category: "database",
    description: "Hosted Postgres with realtime, auth, storage and edge functions.",
    pricing: "Free tier (500MB DB), Pro from $25/mo",
    freeTier: true,
    docsUrl: "https://supabase.com/docs",
    pros: ["Postgres + RLS", "Realtime subscriptions", "Generous free tier"],
    cons: ["Free projects pause after inactivity"],
    installCommands: ["npm install @supabase/supabase-js"],
    envVars: ["NEXT_PUBLIC_SUPABASE_URL", "NEXT_PUBLIC_SUPABASE_ANON_KEY"],
    platforms: ["web", "mobile", "backend", "saas", "agentic"],
    priority: 1,
  },
  {
    id: "postgresql",
    name: "PostgreSQL (self-hosted)",
    category: "database",
    description: "The world's most advanced open-source relational database.",
    pricing: "Free; hosting costs vary",
    freeTier: true,
    docsUrl: "https://www.postgresql.org/docs",
    pros: ["Full control", "No vendor lock-in", "Battle tested"],
    cons: ["You manage backups, scaling and security"],
    installCommands: ["npm install pg"],
    envVars: ["DATABASE_URL"],
    platforms: ["web", "backend", "saas", "agentic"],
    priority: 2,
  },
  {
    id: "mongodb",
    name: "MongoDB Atlas",
    category: "database",
    description: "Hosted document database with a flexible schema.",
    pricing: "Free M0 tier, paid from ~$9/mo",
    freeTier: true,
    docsUrl: "https://www.mongodb.com/docs/atlas",
    pros: ["Flexible documents", "Easy horizontal scaling"],
    cons: ["Weaker relational guarantees", "Query model differs from SQL"],
    installCommands: ["npm install mongodb"],
    envVars: ["MONGODB_URI"],
    platforms: ["web", "backend", "saas", "agentic"],
    priority: 3,
  },
  // --- AI ---
  {
    id: "gemini",
    name: "Google Gemini",
    category: "ai",
    description: "Google's multimodal LLM API with a generous free tier.",
    pricing: "Generous free tier; pay-as-you-go beyond",
    freeTier: true,
    docsUrl: "https://ai.google.dev/gemini-api/docs",
    pros: ["Best free tier among major providers", "Long context", "Multimodal"],
    cons: ["Rate limits on free tier"],
    installCommands: ["npm install @google/generative-ai"],
    envVars: ["GEMINI_API_KEY"],
    platforms: ["web", "mobile", "backend", "saas", "agentic"],
    priority: 1,
  },
  {
    id: "openai",
    name: "OpenAI",
    category: "ai",
    description: "GPT model family API for chat, embeddings and tools.",
    pricing: "Pay-as-you-go, no free tier",
    freeTier: false,
    docsUrl: "https://platform.openai.com/docs",
    pros: ["Strong tool-calling", "Large ecosystem"],
    cons: ["No free tier", "Costs scale with usage"],
    installCommands: ["npm install openai"],
    envVars: ["OPENAI_API_KEY"],
    platforms: ["web", "mobile", "backend", "saas", "agentic"],
    priority: 2,
  },
  {
    id: "anthropic",
    name: "Anthropic Claude",
    category: "ai",
    description: "Claude model family API, strong at reasoning and coding.",
    pricing: "Pay-as-you-go, no free tier",
    freeTier: false,
    docsUrl: "https://docs.anthropic.com",
    pros: ["Excellent long-form reasoning", "Large context windows"],
    cons: ["No free tier"],
    installCommands: ["npm install @anthropic-ai/sdk"],
    envVars: ["ANTHROPIC_API_KEY"],
    platforms: ["web", "mobile", "backend", "saas", "agentic"],
    priority: 3,
  },
  // --- Video ---
  {
    id: "stream",
    name: "Stream Video",
    category: "video",
    description: "Hosted video calling, livestreaming and chat SDKs.",
    pricing: "Free maker plan for small apps; paid from $499/mo",
    freeTier: true,
    docsUrl: "https://getstream.io/video/docs",
    pros: ["Polished SDKs for React/React Native", "Chat included"],
    cons: ["Expensive at scale"],
    installCommands: ["npm install @stream-io/video-react-sdk"],
    envVars: ["STREAM_API_KEY", "STREAM_API_SECRET"],
    platforms: ["web", "mobile", "saas"],
    priority: 1,
  },
  {
    id: "livekit",
    name: "LiveKit",
    category: "video",
    description: "Open-source WebRTC infrastructure, cloud or self-hosted.",
    pricing: "Free cloud tier; self-hosting is free",
    freeTier: true,
    docsUrl: "https://docs.livekit.io",
    pros: ["Open source", "Self-host option", "Good realtime AI support"],
    cons: ["More setup than Stream"],
    installCommands: ["npm install livekit-client"],
    envVars: ["LIVEKIT_API_KEY", "LIVEKIT_API_SECRET", "LIVEKIT_URL"],
    platforms: ["web", "mobile", "saas", "agentic"],
    priority: 2,
  },
  // --- Storage ---
  {
    id: "supabase-storage",
    name: "Supabase Storage",
    category: "storage",
    description: "S3-compatible object storage bundled with Supabase.",
    pricing: "1GB free, then usage-based",
    freeTier: true,
    docsUrl: "https://supabase.com/docs/guides/storage",
    pros: ["Integrates with Supabase auth/RLS", "Simple API"],
    cons: ["Tied to Supabase"],
    installCommands: ["npm install @supabase/supabase-js"],
    envVars: ["NEXT_PUBLIC_SUPABASE_URL", "NEXT_PUBLIC_SUPABASE_ANON_KEY"],
    platforms: ["web", "mobile", "backend", "saas", "agentic", "chrome-extension"],
    priority: 1,
  },
  {
    id: "cloudflare-r2",
    name: "Cloudflare R2",
    category: "storage",
    description: "S3-compatible object storage with zero egress fees.",
    pricing: "10GB free, no egress fees",
    freeTier: true,
    docsUrl: "https://developers.cloudflare.com/r2",
    pros: ["No egress fees", "S3 compatible"],
    cons: ["Requires Cloudflare account setup"],
    installCommands: ["npm install @aws-sdk/client-s3"],
    envVars: ["R2_ACCOUNT_ID", "R2_ACCESS_KEY_ID", "R2_SECRET_ACCESS_KEY"],
    platforms: ["web", "backend", "saas", "agentic", "chrome-extension"],
    priority: 2,
  },
  // --- Email ---
  {
    id: "resend",
    name: "Resend",
    category: "email",
    description: "Developer-first transactional email API with React Email support.",
    pricing: "3,000 emails/mo free, then from $20/mo",
    freeTier: true,
    docsUrl: "https://resend.com/docs",
    pros: ["Great DX", "React Email templates", "Generous free tier"],
    cons: ["Younger than SendGrid/Mailgun"],
    installCommands: ["npm install resend"],
    envVars: ["RESEND_API_KEY"],
    platforms: ["web", "backend", "saas"],
    priority: 1,
  },
  // --- Payments ---
  {
    id: "stripe",
    name: "Stripe",
    category: "payments",
    description: "Industry-standard payments, subscriptions and billing.",
    pricing: "No monthly fee; 2.9% + 30c per transaction",
    freeTier: false,
    docsUrl: "https://docs.stripe.com",
    pros: ["Best-in-class docs", "Subscriptions, invoicing, tax"],
    cons: ["Transaction fees", "Complex for advanced billing"],
    installCommands: ["npm install stripe"],
    envVars: ["STRIPE_SECRET_KEY", "STRIPE_WEBHOOK_SECRET"],
    platforms: ["web", "mobile", "backend", "saas"],
    priority: 1,
  },
  // --- Analytics ---
  {
    id: "posthog",
    name: "PostHog",
    category: "analytics",
    description: "Open-source product analytics, session replay and feature flags.",
    pricing: "1M events/mo free, then usage-based",
    freeTier: true,
    docsUrl: "https://posthog.com/docs",
    pros: ["All-in-one product suite", "Self-host option", "Generous free tier"],
    cons: ["UI can feel dense"],
    installCommands: ["npm install posthog-js"],
    envVars: ["NEXT_PUBLIC_POSTHOG_KEY", "NEXT_PUBLIC_POSTHOG_HOST"],
    platforms: ["web", "mobile", "saas", "chrome-extension"],
    priority: 1,
  },
  // --- Monitoring ---
  {
    id: "sentry",
    name: "Sentry",
    category: "monitoring",
    description: "Error tracking and performance monitoring.",
    pricing: "Free developer tier, paid from $26/mo",
    freeTier: true,
    docsUrl: "https://docs.sentry.io",
    pros: ["Rich error context", "Wide SDK coverage"],
    cons: ["Quota limits on free tier"],
    installCommands: ["npm install @sentry/nextjs"],
    envVars: ["SENTRY_DSN"],
    platforms: ["web", "mobile", "backend", "saas", "agentic"],
    priority: 1,
  },
  // --- Styling ---
  {
    id: "tailwind",
    name: "Tailwind CSS",
    category: "styling",
    description: "Utility-first CSS framework.",
    pricing: "Free and open source",
    freeTier: true,
    docsUrl: "https://tailwindcss.com/docs",
    pros: ["Fast iteration", "Design consistency via tokens"],
    cons: ["Verbose class lists"],
    installCommands: ["npm install -D tailwindcss postcss autoprefixer"],
    envVars: [],
    platforms: ["web", "saas", "chrome-extension"],
    priority: 1,
  },
  {
    id: "nativewind",
    name: "NativeWind",
    category: "styling",
    description: "Tailwind CSS for React Native.",
    pricing: "Free and open source",
    freeTier: true,
    docsUrl: "https://www.nativewind.dev",
    pros: ["Tailwind syntax on mobile", "Shared design language with web"],
    cons: ["Subset of Tailwind features"],
    installCommands: ["npm install nativewind", "npm install -D tailwindcss"],
    envVars: [],
    platforms: ["mobile"],
    priority: 1,
  },
];

export function getTechnologyById(id: string): Technology | undefined {
  return TECHNOLOGIES.find((t) => t.id === id);
}
