import type { ProjectSpec, ArchitecturalRequirements } from "../../types/projectspec";

/**
 * Generates `requirements.md` — a formal, human-readable requirement document
 * derived from the ArchitecturalRequirements extracted by the pipeline.
 *
 * This file is included in every generated package so both the developer
 * and AI coding agents can read exactly what the system must do before
 * writing a single line of implementation code.
 */
export function generateRequirementsDoc(spec: ProjectSpec): string {
  const req = spec.architecturalRequirements as ArchitecturalRequirements | undefined;
  if (!req) return generateMinimalRequirementsDoc(spec);

  const now = new Date().toISOString().split("T")[0];

  // ── Functional requirements table ─────────────────────────────────────────
  const frRows = req.functional
    .map(
      (r) =>
        `| ${r.id} | ${r.title} | ${r.type === "implicit" ? "🔵 Implicit" : "🟢 Explicit"} | ${r.priority} | ${r.actors.join(", ")} |`,
    )
    .join("\n");

  const frDetails = req.functional
    .map(
      (r) => `### ${r.id} — ${r.title}
- **Type:** ${r.type === "implicit" ? "Implicit (inferred by architect)" : "Explicit (stated in description)"}
- **Priority:** ${r.priority}
- **Actors:** ${r.actors.join(", ")}
- **Description:** ${r.description}`,
    )
    .join("\n\n");

  // ── NFR sections ──────────────────────────────────────────────────────────
  function nfrSection(label: string, items: string[]): string {
    if (items.length === 0) return "";
    return `\n#### ${label}\n${items.map((i) => `- ${i}`).join("\n")}`;
  }

  const nfrContent = [
    nfrSection("⚡ Performance", req.nonFunctional.performance),
    nfrSection("🔒 Security", req.nonFunctional.security),
    nfrSection("📈 Scalability", req.nonFunctional.scalability),
    nfrSection("🟢 Availability", req.nonFunctional.availability),
    nfrSection("♿ Accessibility", req.nonFunctional.accessibility),
    nfrSection("⚖️ Compliance & Regulatory", req.nonFunctional.compliance),
    nfrSection("🔧 Maintainability", req.nonFunctional.maintainability),
    nfrSection("📝 Other", req.nonFunctional.other),
  ]
    .filter(Boolean)
    .join("\n");

  // ── Domain entities ───────────────────────────────────────────────────────
  const entityDocs = req.domain.entities
    .map(
      (e) => `### ${e.name}
${e.description}

**Attributes:** ${e.attributes.join(", ")}
${e.relatedEntities.length ? `**Relates to:** ${e.relatedEntities.join(", ")}` : ""}`,
    )
    .join("\n\n");

  // ── Actor docs ────────────────────────────────────────────────────────────
  const actorDocs = req.domain.actors
    .map(
      (a) => `### ${a.name}
${a.description}
${a.permissions?.length ? `\n**Permissions:** ${a.permissions.join(", ")}` : ""}`,
    )
    .join("\n\n");

  // ── Edge cases table ──────────────────────────────────────────────────────
  const edgeRows = req.edgeCases
    .map(
      (e) =>
        `| \`${e.category}\` | ${e.scenario} | ${e.expectedBehaviour} |`,
    )
    .join("\n");

  // ── Hard constraints ──────────────────────────────────────────────────────
  const c = req.constraints;
  const constraintLines: string[] = [];
  if (c.mustBeOffline) constraintLines.push("- 🚫 **Fully offline** — no internet access permitted at runtime");
  if (c.mustUseLocalStorage) constraintLines.push("- 🚫 **Local storage only** — no cloud database");
  if (c.forbiddenTools.length) constraintLines.push(`- 🚫 **Forbidden tools:** ${c.forbiddenTools.join(", ")}`);
  if (c.forbiddenCategories.length) constraintLines.push(`- 🚫 **Forbidden categories:** ${c.forbiddenCategories.join(", ")}`);
  if (c.requiredToolTypes.length) constraintLines.push(`- ✅ **Required tool types:** ${c.requiredToolTypes.join(", ")}`);
  if (c.compliance?.length) constraintLines.push(`- ⚖️ **Compliance:** ${c.compliance.join(", ")}`);
  if (c.budgetConstraint) constraintLines.push(`- 💰 **Budget constraint:** ${c.budgetConstraint}`);
  if (c.rawConstraints.length) {
    constraintLines.push("\n**Raw constraint quotes from description:**");
    c.rawConstraints.forEach((rc) => constraintLines.push(`  - "${rc}"`));
  }

  return `# Requirements — ${spec.projectName}

> Generated by ContextForge requirement extraction pipeline on ${now}
> This document was produced by a Software Architect reasoning engine, not keyword extraction.

---

## 1. Business Goals

${req.businessGoals.map((g) => `- ${g}`).join("\n")}

---

## 2. Success Criteria

The project is considered successful when:

${req.successCriteria.map((c, i) => `${i + 1}. ${c}`).join("\n")}

---

## 3. Target Audience

${req.targetAudience.map((a) => `- ${a}`).join("\n")}

---

## 4. Domain Model

### 4.1 Actors (User Roles)

${actorDocs}

### 4.2 Core Entities

${entityDocs}

### 4.3 Core Workflows

${req.domain.coreWorkflows.map((w, i) => `${i + 1}. ${w}`).join("\n")}

---

## 5. Functional Requirements

| ID | Title | Type | Priority | Actors |
|----|-------|------|----------|--------|
${frRows}

### Detailed Descriptions

${frDetails}

---

## 6. Non-Functional Requirements

${nfrContent}

---

## 7. Edge Cases & Failure Modes

> These scenarios MUST be handled gracefully. Do not treat them as optional.

| Category | Scenario | Expected Behaviour |
|----------|----------|--------------------|
${edgeRows}

---

## 8. Hard Technical Constraints

${constraintLines.length ? constraintLines.join("\n") : "_No hard constraints detected._"}

---

## 9. Implicit Requirements Checklist

The following requirements were **inferred** by the architect and were **not explicitly stated** in the project description. Verify each one with the product owner before implementation.

${req.functional
  .filter((r) => r.type === "implicit")
  .map((r) => `- [ ] **${r.id} — ${r.title}:** ${r.description}`)
  .join("\n") || "_All requirements are explicitly stated._"}

---

*This file is auto-generated. To update it, re-run the ContextForge generation pipeline with an updated project description.*
`;
}

/** Minimal fallback when no ArchitecturalRequirements are present */
function generateMinimalRequirementsDoc(spec: ProjectSpec): string {
  const now = new Date().toISOString().split("T")[0];
  const c = spec.constraints;

  return `# Requirements — ${spec.projectName}

> Generated by ContextForge on ${now} (heuristic mode — no AI extraction performed)

## Project Description

${spec.description}

## Platform

${spec.platform}

## Features

${spec.features.map((f) => `- ${f}`).join("\n") || "_None listed._"}

## Declared Constraints

${c.budget ? `- **Budget:** ${c.budget}` : ""}
${c.avoid?.length ? `- **Avoid:** ${c.avoid.join(", ")}` : ""}
${c.technical?.mustBeOffline ? "- 🚫 Fully offline" : ""}
${c.technical?.forbiddenTools?.length ? `- 🚫 Forbidden: ${c.technical.forbiddenTools.join(", ")}` : ""}

---

*Re-run with an AI provider configured (ANTHROPIC_API_KEY / XAI_API_KEY / NVIDIA_API_KEY / GROQ_API_KEY) to get a full architectural requirement extraction.*
`;
}
