import type { ProjectSpec, ArchitecturalRequirements } from "../../types/projectspec";

/**
 * Generates `requirements.md` — a formal, human-readable requirement document
 * derived from the ArchitecturalRequirements extracted by the pipeline.
 *
 * This file is included in every generated package so both the developer
 * and AI coding agents can read exactly what the system must do before
 * writing a single line of implementation code.
 */
export function generateRequirementsDoc(spec: ProjectSpec): string {
  const req = spec.architecturalRequirements as ArchitecturalRequirements | undefined;
  if (!req) return generateMinimalRequirementsDoc(spec);

  const now = new Date().toISOString().split("T")[0];

  // ── Functional requirements table ─────────────────────────────────────────
  const frRows = req.functional
    .map(
      (r) =>
        `| ${r.id} | ${r.title} | ${r.type === "implicit" ? "🔵 Implicit" : "🟢 Explicit"} | ${r.priority} | ${r.actors.join(", ")} |`,
    )
    .join("\n");

  const frDetails = req.functional
    .map(
      (r) => `### ${r.id} — ${r.title}
- **Type:** ${r.type === "implicit" ? "Implicit (inferred by architect)" : "Explicit (stated in description)"}
- **Priority:** ${r.priority}
- **Actors:** ${r.actors.join(", ")}
- **Description:** ${r.description}`,
    )
    .join("\n\n");

  // ── NFR sections ──────────────────────────────────────────────────────────
  function nfrSection(label: string, items: string[]): string {
    if (items.length === 0) return "";
    return `\n#### ${label}\n${items.map((i) => `- ${i}`).join("\n")}`;
  }

  const nfrContent = [
    nfrSection("⚡ Performance", req.nonFunctional.performance),
    nfrSection("🔒 Security", req.nonFunctional.security),
    nfrSection("📈 Scalability", req.nonFunctional.scalability),
    nfrSection("🟢 Availability", req.nonFunctional.availability),
    nfrSection("♿ Accessibility", req.nonFunctional.accessibility),
    nfrSection("⚖️ Compliance & Regulatory", req.nonFunctional.compliance),
    nfrSection("🔧 Maintainability", req.nonFunctional.maintainability),
    nfrSection("📝 Other", req.nonFunctional.other),
  ]
    .filter(Boolean)
    .join("\n");

  // ── Domain entities ───────────────────────────────────────────────────────
  const entityDocs = req.domain.entities
    .map(
      (e) => `### ${e.name}
${e.description}

**Attributes:** ${e.attributes.join(", ")}
${e.relatedEntities.length ? `**Relates to:** ${e.relatedEntities.join(", ")}` : ""}`,
    )
    .join("\n\n");

  // ── Actor docs ────────────────────────────────────────────────────────────
  const actorDocs = req.domain.actors
    .map(
      (a) => `### ${a.name}
${a.description}
${a.permissions?.length ? `\n**Permissions:** ${a.permissions.join(", ")}` : ""}`,
    )
    .join("\n\n");

  // ── Edge cases table ──────────────────────────────────────────────────────
  const edgeRows = req.edgeCases
    .map(
      (e) =>
        `| \`${e.category}\` | ${e.scenario} | ${e.expectedBehaviour} |`,
    )
    .join("\n");

  // ── Hard constraints ──────────────────────────────────────────────────────
  const c = req.constraints;
  const constraintLines: string[] = [];
  if (c.mustBeOffline) constraintLines.push("- 🚫 **Fully offline** — no internet access permitted at runtime");
  if (c.mustUseLocalStorage) constraintLines.push("- 🚫 **Local storage only** — no cloud database");
  if (c.forbiddenTools.length) constraintLines.push(`- 🚫 **Forbidden tools:** ${c.forbiddenTools.join(", ")}`);
  if (c.forbiddenCategories.length) constraintLines.push(`- 🚫 **Forbidden categories:** ${c.forbiddenCategories.join(", ")}`);
  if (c.requiredToolTypes.length) constraintLines.push(`- ✅ **Required tool types:** ${c.requiredToolTypes.join(", ")}`);
  if (c.compliance?.length) constraintLines.push(`- ⚖️ **Compliance:** ${c.compliance.join(", ")}`);
  if (c.budgetConstraint) constraintLines.push(`- 💰 **Budget constraint:** ${c.budgetConstraint}`);
  if (c.rawConstraints.length) {
    constraintLines.push("\n**Raw constraint quotes from description:**");
    c.rawConstraints.forEach((rc) => constraintLines.push(`  - "${rc}"`));
  }

  return `# Requirements — ${spec.projectName}

> Generated by ContextForge requirement extraction pipeline on ${now}
> This document was produced by a Software Architect reasoning engine, not keyword extraction.

---

## 1. Business Goals

${req.businessGoals.map((g) => `- ${g}`).join("\n")}

---

## 2. Success Criteria

The project is considered successful when:

${req.successCriteria.map((c, i) => `${i + 1}. ${c}`).join("\n")}

---

## 3. Target Audience

${req.targetAudience.map((a) => `- ${a}`).join("\n")}

---

## 4. Domain Model

### 4.1 Actors (User Roles)

${actorDocs}

### 4.2 Core Entities

${entityDocs}

### 4.3 Core Workflows

${req.domain.coreWorkflows.map((w, i) => `${i + 1}. ${w}`).join("\n")}

---

## 5. Functional Requirements

| ID | Title | Type | Priority | Actors |
|----|-------|------|----------|--------|
${frRows}

### Detailed Descriptions

${frDetails}

---

## 6. Non-Functional Requirements

${nfrContent}

---

## 7. Edge Cases & Failure Modes

> These scenarios MUST be handled gracefully. Do not treat them as optional.

| Category | Scenario | Expected Behaviour |
|----------|----------|--------------------|
${edgeRows}

---

## 8. Hard Technical Constraints

${constraintLines.length ? constraintLines.join("\n") : "_No hard constraints detected._"}

---

## 9. Implicit Requirements Checklist

The following requirements were **inferred** by the architect and were **not explicitly stated** in the project description. Verify each one with the product owner before implementation.

${req.functional
  .filter((r) => r.type === "implicit")
  .map((r) => `- [ ] **${r.id} — ${r.title}:** ${r.description}`)
  .join("\n") || "_All requirements are explicitly stated._"}

---

*This file is auto-generated. To update it, re-run the ContextForge generation pipeline with an updated project description.*
`;
}

/** Minimal fallback when no ArchitecturalRequirements are present */
function generateMinimalRequirementsDoc(spec: ProjectSpec): string {
  const now = new Date().toISOString().split("T")[0];
  const c = spec.constraints;

  const frRows = spec.features.map((f, i) => {
    const id = `FR-${(i + 1).toString().padStart(2, '0')}`;
    let priority = "Medium";
    if (i === 0 || /auth|login|account|payment|core/i.test(f)) priority = "High";
    if (/export|settings|admin|notification/i.test(f)) priority = "Low";
    return `| ${id} | ${f} | 🟢 Explicit | ${priority} | Primary User |`;
  }).join("\n");

  const frDetails = spec.features.map((f, i) => {
    const id = `FR-${(i + 1).toString().padStart(2, '0')}`;
    let desc = `The system shall provide the ability to ${f.toLowerCase()}.`;
    if (/auth|login/i.test(f)) desc = `The system shall authenticate users securely and restrict access to protected resources.`;
    if (/payment|billing/i.test(f)) desc = `The system shall process payments securely and provision access based on subscription status.`;
    return `### ${id} — ${f}\n- **Type:** Explicit (stated in description)\n- **Actors:** Primary User\n- **Description:** ${desc}`;
  }).join("\n\n");

  const isMobile = spec.platform.toLowerCase().includes('mobile');
  const nfrs = [
    `\n#### ⚡ Performance\n- Core interactions must respond within 200ms.\n- Application must load and be interactive within 3 seconds.`,
    `\n#### 🔒 Security\n- All data transmitted over TLS (HTTPS/WSS).\n- User data strictly isolated by tenant/account.`,
    `\n#### ♿ Accessibility\n- Must meet WCAG 2.1 AA standards for contrast and keyboard navigation.${isMobile ? '\n- Minimum touch target size of 44x44pt.' : ''}`,
  ].join("\n");

  return `# Requirements — ${spec.projectName}

> Generated by ContextForge on ${now} (heuristic mode — no AI extraction performed)
> Re-run with an AI provider configured to get a full architectural requirement extraction.

---

## 1. Project Overview

${spec.description}

**Platform:** ${spec.platform}

---

## 2. Functional Requirements

| ID | Title | Type | Priority | Actors |
|----|-------|------|----------|--------|
${frRows || "| FR-01 | Core Functionality | 🟢 Explicit | High | Primary User |"}

### Detailed Descriptions

${frDetails || "### FR-01 — Core Functionality\n- **Description:** The system shall implement the core functionality described in the project overview."}

---

## 3. Non-Functional Requirements (Baseline)

${nfrs}

---

## 4. Declared Constraints

${c.budget ? `- 💰 **Budget:** ${c.budget}` : ""}
${c.avoid?.length ? `- 🚫 **Avoid:** ${c.avoid.join(", ")}` : ""}
${c.technical?.mustBeOffline ? "- 🚫 **Fully offline:** No internet access permitted at runtime" : ""}
${c.technical?.forbiddenTools?.length ? `- 🚫 **Forbidden:** ${c.technical.forbiddenTools.join(", ")}` : ""}
${!c.budget && !c.avoid?.length && !c.technical?.mustBeOffline && !c.technical?.forbiddenTools?.length ? "_No hard constraints declared._" : ""}
`;
}
